### ISSUE TITLE
BlazorLibrary not working with Codespaces

### ISSUE THREAD

**Issue by dajma00** [Blazor-School/Blazor-Library-Public-Issue-Tracker#2]
I have a project using BlazorLibrary. It works fine on local machine and deployment machine. However, with Github Codespaces, the app crashes with this message:
```
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '0J29eWFlzxc60QQHfWZlWhEWkIfDTW_o4L40QSZTHDY'.
      System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
       ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
         at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
         at BlazorSchool.Components.Web.Theme.Data.ThemePack.FromJson(String json)
         at BlazorSchool.Components.Web.Theme.BlazorApplyTheme.ThemePackPathUpdate(HttpClient httpClient, IReadOnlyDictionary`2 parameterDictionary)
         at BlazorSchool.Components.Web.Theme.BlazorApplyTheme.SetParametersAsync(ParameterView parameters)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
Any ideas why? Looks like BlazorLibrary trying to get some data but failing.

**Comment by hevilhuy** [comment]
I think the https://<yourdomain.com>/_content/BlazorSchool.Components.Web/Themes/Default/default.min.json is not accessible

**Comment by dajma00** [comment]
hmm.... why the issue on Codespaces only?

**Comment by hevilhuy** [comment]
> hmm.... why the issue on Codespaces only?

I don't know yet. But https://<yourdomain.com>/_content/BlazorSchool.Components.Web/Themes/Default/default.min.json is accessible?

**Comment by dajma00** [comment]
Not sure, but if that was the case, why would it work on my development machine as well as live deployment machine?

**Comment by hevilhuy** [comment]
Please check the URL.
